# Generated by Django 2.2.10 on 2020-03-20 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('show_timing1', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_timing2', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_timing3', models.DateTimeField(default=django.utils.timezone.now)),
                ('show_timing4', models.DateTimeField(default=django.utils.timezone.now)),
                ('Tickets_available', models.IntegerField(default=100)),
                ('Tickets_booked', models.IntegerField(default=0)),
            ],
        ),
    ]
