# Generated by Django 2.2.10 on 2020-03-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
