# Generated by Django 2.2.10 on 2020-03-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0002_moviedetails_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedetails',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
